# Generated by Django 5.2.1 on 2025-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Введите заголовок", max_length=250, verbose_name="Заголовок")),
                ("content", models.TextField(help_text="Заполните содержимое", verbose_name="Содержимое")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blogphotos",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True, help_text="Укажите дату создания", null=True, verbose_name="Дата создания"
                    ),
                ),
                ("publication_attribute", models.BooleanField(default=False)),
                (
                    "views_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        null=True,
                        verbose_name="Счетчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ["title", "created_at", "publication_attribute", "views_quantity"],
            },
        ),
    ]
