# Generated by Django 5.2.1 on 2025-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату создания продукта",
                null=True,
                verbose_name="Дата создания продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фотографию продукта",
                null=True,
                upload_to="photos",
                verbose_name="Изображение продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату последнего изменения продукта",
                null=True,
                verbose_name="Дата последнего изменения продукта",
            ),
        ),
    ]
