# Generated by Django 5.2.1 on 2025-08-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(help_text="Укажите цену продукта", verbose_name="Цена продукта"),
        ),
    ]
