# Generated by Django 5.2.1 on 2025-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publish_product",
            field=models.BooleanField(
                default=False,
                help_text="Укажите статус публикации продукта.",
                verbose_name="Статус публикации продукта",
            ),
        ),
    ]
